global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.15.56:9090','10.0.14.30:9100','10.0.6.101:9100']
